# Use root/example as user/password credentials
version: '3.1'

services:
  mariadb:
    image: mariadb:latest
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: myapp
    ports:
      - 3309:3306
    volumes:
      - /apps/mariadb:/var/lib/mysql
      